### ISSUE TITLE
Cannot import wikipedia_nrc.dump into neo4j 4.0.3 

### ISSUE THREAD

**Issue by movingname** [epfl-lts2/sparkwiki#17]
Hello,

First thank you for creating this great project!

I am trying to import wikipedia_nrc.dump into neo4j 4.0.3 using the following command from https://lts2.epfl.ch/Datasets/Wikipedia/

`neo4j-admin load --from=wikipedia_nrc.dump --database=wikipedia.db`

The command worked and I can see a wikipedia.db directory created in neo4j's databases directory, with all the database files.

However, when I want to use cypher-shell to connect, I keep getting the error:

`Unable to get a routing table for database 'wikipedia.db' because this database is unavailable`

I already set the default_database configuration, and I confirm that it works for the odefault neo4j database.
`dbms.default_database=wikipedia.db`

I checked around and found some guides in https://github.com/epfl-lts2/sparkwiki/tree/master/helpers But it only applies to csv dumps, not the single dump file.

Any help is appreciated. Thank you!

**Comment by naspert** [comment]
Hello
We only used neo4j v3 when developing. However I succeeded in importing the dump into version 4.0.3. 
You need to set `dbms.allow_upgrade=true` in `/etc/neo4j/neo4j.conf`
When you (re)start neo4j it should upgrade the database (takes a while depending on your system) and then the database should be accessible. 
Another thing to check is that the import is done with correct permissions, s.t. the db directory has proper ownership set. The command
`sudo -u neo4j neo4j-admin load --force --from=wikipedia_nrc.dump --database=wikipedia.db`
worked for me.
Let me know if you succeed, if not can you attach the relevant part of `/var/log/neo4j/debug.log` ?

Best regards

**Comment by movingname** [comment]
Wow, `dbms.allow_upgrade=true` saved my day. Thank you so much!

**Comment by naspert** [comment]
you're welcome :)
