### ISSUE TITLE
Value %% is not a member of String error when building

### ISSUE THREAD

**Issue by sabetAI** [epfl-lts2/sparkwiki#2]
I'm getting the following error when trying calling `sbt package` in the `project` directory:

```
/sparkwiki/project/Dependencies.scala:4:40: value %% is not a member of String
lazy val scalaTest = "org.scalatest" %% "scalatest" % "3.0.5"
```

scala version: 2.11.12
spark version: 2.2.3

**Comment by mizvol** [comment]
Could you please check your `sbt` version?

**Comment by mizvol** [comment]
Tested. Cannot reproduce.

**OS:** Ubuntu 18.04.02 LTS, MacOS 10.14 Mojave
**sbt**: 1.2.8 
**Scala**: 2.11.12
**Spark**: 2.2.1
