### ISSUE TITLE
dump processor in endless loop

### ISSUE THREAD

**Issue by kaikugler** [epfl-lts2/sparkwiki#5]
dump processor doesn't dump anything. directory /pagelinks/_temporary/0 is created, last terminal logs: 
```
INFO compress.CodecPool: Got brand-new decompressor [.bz2]
INFO codegen.CodeGenerator: Code generated in 76.342234 ms
```

**Comment by naspert** [comment]
table structure has changed since the release (we were using a dump from 2018). Fix is underway.

**Comment by naspert** [comment]
@JuliusHibbert can you confirm that version 0.9.6 fixed the issue for you ?

**Comment by kaikugler** [comment]
yes, i can confirm the dumps (enwiki-20190601) get processed now. thanks a lot!
```
spark.SparkContext: Successfully stopped SparkContext
INFO util.ShutdownHookManager: Shutdown hook called
INFO util.ShutdownHookManager: Deleting directory /tmp/...
```
