### ISSUE TITLE
import-script doesn't work

### ISSUE THREAD

**Issue by kaikugler** [epfl-lts2/sparkwiki#7]
the import script ("Import the pre-processed files in Neo4J") doesn't work.
neo4j-admin 3.5.6
error: `Directory of import/page_header.csv doesn't exist`

parameter for node-files should be something like
`neo4j-admin import --nodes[:Label1:Label2]=<"file1,file2">`

**Comment by mizvol** [comment]
I guess the tutorial doesn't explain that step in much detail. 

Seems like the script doesn't see `import` folder with header files. 

To solve the problem, I'd recommend to do it in the following way:
1. Download `import` folder with header files from [this](https://github.com/epfl-lts2/sparkwiki/tree/master/helpers/import) location.
2. Create a script file (say, name it `import-neo4j.sh`) and put it into the same folder with the `import` folder.
3. Run the script from the command line entering the following command `./import-neo4j.sh`.

Let me know if you still get the error after performing the steps above.
